$color = rgba(28, 27, 25, 1)
$inner_color = rgba(28, 27, 25, 1)
$outer_color = rgba(212, 189, 153, 1)
$font_color = rgba(240, 228, 197, 1)
$placeholder_color = rgba(168, 153, 132, 0.7)
$check_color = rgba(231, 192, 124, 1)
