name: Aether
accent: "#706e6b"
cursor: "#706e6b"
background: "#1c1b19"
foreground: "#f0e4c5"
details: darker

terminal_colors:
  normal:
    black:   "#1c1b19"
    red:     "#c5564a"
    green:   "#a89984"
    yellow:  "#ebdbb2"
    blue:    "#908d88"
    magenta: "#afa499"
    cyan:    "#d4bd99"
    white:   "#fbf1c7"
  bright:
    black:   "#6b655c"
    red:     "#d94e38"
    green:   "#c2a571"
    yellow:  "#f7df97"
    blue:    "#aaa090"
    magenta: "#cbae8e"
    cyan:    "#e7c07c"
    white:   "#fff8e8"
